backend:
  name: github
  repo: sercancicek/netlify-demo

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{slug}"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/homeMD/home.md"
        fields:
          - {label: Title, name: h1, widget: string}
          - {label: Sub Title, name: h2, widget: string}
          - {label: Paragraph, name: p, widget: string}